apiVersion: apps/v1
kind: Deployment
metadata:
 name : Spring-boot-app
 labels:
  app: spring-boot-app
spec:
  replicas: 4
  selector:
   matchLabels:
    app: spring-boot-app
  template:
   metadata:
    labels:
     app: spring-boot-app
   spec:
    containers:
     - name: spring-boot-app
       image: supriyohub/ci-cd-jenkins-docker-argocd-k8s:71
       ports:
        - containerPort: 8080
